title: Cookbook
description: Recipe collection 
baseurl: "/cookbook" # repository name for a project site
url: "https://oliviagallucci.github.io" # pages root domain
markdown: kramdown
theme: minima
# exclude non-site artifacts
exclude:
  - LICENSE
collections: []
